run:
  concurrency: 4
  deadline: 1m
  tests: true
linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - goconst
    - gocritic
    - gofmt
    - goimports
    - golint
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - structcheck
    - unconvert
    - unparam
    - varcheck
