language: go

os:
  - linux

go:
  - "1.8"
  - "1.12"

before_install:
  - go get -u github.com/rakyll/gotest
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.16.0

install:
  - make deps
  - make generate
  - make lint

script:
  - make test

env:
  - PATH=:./bin/:${PATH}
